WITH SUB AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) M
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A join SUB B
ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = M
ORDER BY A.FOOD_TYPE DESC