-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', C.BOARD_ID,'/',D.FILE_ID,D.FILE_NAME,D.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD C JOIN USED_GOODS_FILE D ON C.BOARD_ID=D.BOARD_ID
WHERE C.BOARD_ID=
(SELECT A.BOARD_ID
FROM USED_GOODS_BOARD A JOIN USED_GOODS_FILE B ON A.BOARD_ID=B.BOARD_ID
GROUP BY A.BOARD_ID
ORDER BY SUM(VIEWS) DESC
LIMIT 1)
ORDER BY D.FILE_ID DESC
